# SpellRight configuration
ignore:
  - proguard
  - gradle
  - keepclassmembers
  - keepattributes
  - renamesourcefileattribute
  - dontwarn
  - keepnames
  - allowobfuscation
  - allowshrinking
  - assumenosideeffects
  - obfuscationdictionary
  - classobfuscationdictionary
  - packageobfuscationdictionary
  - allowaccessmodification
  - dontpreverify
  - optimizationpasses
  - dontskipnonpubliclibraryclassmembers
  - printmapping
  - printseeds
  - printusage
  - dontnote
  - keepclasseswithmembers
  - keepclassmembernames
  - androidx
  - javax
  - os
  - ui
  - enum
  - Parcelable
  - init
  - boolean
  - int
  - val
  - const
  - lateinit
  - var
  - url
  - Url
  - ic
  - Gson
  - gson
  - Json
  - Serializer
  - Deserializer
  - Crashlytics
  - crashlytics
  - Firestore
  - firestore
  - bumptech
  - facebook
  - airbnb
  - lottie
  - jetbrains
  - kotlin
  - kotlinx
  - gms
  - Auth
  - iid
  - Fcm
  - Nav
  - Loggable
  - Aalay
  - aalay
  - fqcn
  - webview
  - javascript
ignoreFiles:
  - "*.pro"
