package com.aalay.app.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme Colors
val md_theme_light_primary = Color(0xFF1976D2)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFBBDEFB)
val md_theme_light_onPrimaryContainer = Color(0xFF0D47A1)
val md_theme_light_secondary = Color(0xFFFF7043)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFCCBC)
val md_theme_light_onSecondaryContainer = Color(0xFFD84315)
val md_theme_light_tertiary = Color(0xFF4CAF50)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFC8E6C9)
val md_theme_light_onTertiaryContainer = Color(0xFF2E7D32)
val md_theme_light_error = Color(0xFFF44336)
val md_theme_light_errorContainer = Color(0xFFFFCDD2)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFFB71C1C)
val md_theme_light_background = Color(0xFFFFFFFF)
val md_theme_light_onBackground = Color(0xFF212121)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF212121)
val md_theme_light_surfaceVariant = Color(0xFFF5F5F5)
val md_theme_light_onSurfaceVariant = Color(0xFF757575)
val md_theme_light_outline = Color(0xFFDADCE0)
val md_theme_light_inverseOnSurface = Color(0xFFFFFFFF)
val md_theme_light_inverseSurface = Color(0xFF212121)
val md_theme_light_inversePrimary = Color(0xFFBBDEFB)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF1976D2)
val md_theme_light_outlineVariant = Color(0xFFE0E0E0)
val md_theme_light_scrim = Color(0xFF000000)

// Dark Theme Colors
val md_theme_dark_primary = Color(0xFFBBDEFB)
val md_theme_dark_onPrimary = Color(0xFF0D47A1)
val md_theme_dark_primaryContainer = Color(0xFF1565C0)
val md_theme_dark_onPrimaryContainer = Color(0xFFE3F2FD)
val md_theme_dark_secondary = Color(0xFFFFCCBC)
val md_theme_dark_onSecondary = Color(0xFFD84315)
val md_theme_dark_secondaryContainer = Color(0xFFFF5722)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFF3E0)
val md_theme_dark_tertiary = Color(0xFFC8E6C9)
val md_theme_dark_onTertiary = Color(0xFF2E7D32)
val md_theme_dark_tertiaryContainer = Color(0xFF388E3C)
val md_theme_dark_onTertiaryContainer = Color(0xFFE8F5E8)
val md_theme_dark_error = Color(0xFFFFCDD2)
val md_theme_dark_errorContainer = Color(0xFFD32F2F)
val md_theme_dark_onError = Color(0xFFB71C1C)
val md_theme_dark_onErrorContainer = Color(0xFFFFEBEE)
val md_theme_dark_background = Color(0xFF121212)
val md_theme_dark_onBackground = Color(0xFFFFFFFF)
val md_theme_dark_surface = Color(0xFF1E1E1E)
val md_theme_dark_onSurface = Color(0xFFFFFFFF)
val md_theme_dark_surfaceVariant = Color(0xFF2C2C2C)
val md_theme_dark_onSurfaceVariant = Color(0xFFCCCCCC)
val md_theme_dark_outline = Color(0xFF424242)
val md_theme_dark_inverseOnSurface = Color(0xFF121212)
val md_theme_dark_inverseSurface = Color(0xFFFFFFFF)
val md_theme_dark_inversePrimary = Color(0xFF1976D2)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFBBDEFB)
val md_theme_dark_outlineVariant = Color(0xFF3C3C3C)
val md_theme_dark_scrim = Color(0xFF000000)

// Additional Colors for the App
val PrimaryBlue = Color(0xFF1976D2)
val SecondaryOrange = Color(0xFFFF7043)
val AccentGreen = Color(0xFF4CAF50)
val ErrorRed = Color(0xFFF44336)
val WarningAmber = Color(0xFFFF9800)
val InfoBlue = Color(0xFF2196F3)

// Text Colors
val TextPrimary = Color(0xFF212121)
val TextSecondary = Color(0xFF757575)
val TextDisabled = Color(0xFFBDBDBD)
val TextHint = Color(0xFF9E9E9E)

// Background Colors
val BackgroundPrimary = Color(0xFFFFFFFF)
val BackgroundSecondary = Color(0xFFF5F5F5)
val SurfaceColor = Color(0xFFFFFFFF)

// Status Colors
val SuccessGreen = Color(0xFF4CAF50)
val WarningOrange = Color(0xFFFF9800)
val DangerRed = Color(0xFFF44336)
val InfoCyan = Color(0xFF00BCD4)

// Rating Colors
val RatingExcellent = Color(0xFF4CAF50)
val RatingGood = Color(0xFF8BC34A)
val RatingAverage = Color(0xFFFF9800)
val RatingPoor = Color(0xFFFF5722)
val RatingTerrible = Color(0xFFF44336)

// Transparent Colors
val TransparentWhite = Color(0x80FFFFFF)
val TransparentBlack = Color(0x80000000)
val TransparentGray = Color(0x80757575)
